### ISSUE TITLE
Cheerio 

### ISSUE THREAD

**Issue by GiSi719** [Rifza123/Experimental-Bell#4]
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'

**Comment by Rifza123** [comment]
> SyntaxError: The requested module 'cheerio' does not provide an export named 'default'

use the appropriate version of cheerio 
- npm install cheerio@1.0.0-rc.12

**Comment by GiSi719** [comment]
Done bang, ganti import cheerio from 'cheerio'
Jadi import * as cheerio from 'cheerio'
